name: "Danger"
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  build:
    name: Changelogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

